services:
  typescript-node:
    container_name: typescript-node
    # depends_on:
    #   - typescript-node-db
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    restart: always
    # environment:
    #   - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@typescript-node-db:5432/${POSTGRES_DB}?schema=public
  # typescript-node-db:
  #   container_name: typescript-node-db
  #   image: postgres:latest
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
